"""add user_ra field to disciplina table

Revision ID: 0a8e78f2fbe3
Revises: e18949de1aa9
Create Date: 2025-11-20 00:20:44.755016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8e78f2fbe3'
down_revision: Union[str, Sequence[str], None] = 'e18949de1aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('user_ra', sa.String(length=13), nullable=False))
    op.create_index(op.f('ix_disciplina_user_ra'), 'disciplina', ['user_ra'], unique=False)
    op.create_foreign_key(None, 'disciplina', 'usuario', ['user_ra'], ['ra'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplina', type_='foreignkey')
    op.drop_index(op.f('ix_disciplina_user_ra'), table_name='disciplina')
    op.drop_column('disciplina', 'user_ra')
    # ### end Alembic commands ###
