"""Add disciplina field to docente table

Revision ID: 1b4e1dd2e163
Revises: 1cab29de0c98
Create Date: 2025-11-20 00:19:58.781783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4e1dd2e163'
down_revision: Union[str, Sequence[str], None] = '1cab29de0c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docente', sa.Column('disciplina', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docente', 'disciplina')
    # ### end Alembic commands ###
