"""Add disciplina field and change nota constraints

Revision ID: 1cab29de0c98
Revises: c575db45f179
Create Date: 2025-11-20 00:13:33.668252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cab29de0c98'
down_revision: Union[str, Sequence[str], None] = 'c575db45f179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nota', 'bimestre',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nota', 'nota',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nota', 'nota',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('nota', 'bimestre',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
