"""Add disciplina to horario

Revision ID: 35d3035a0b16
Revises: 1b4e1dd2e163
Create Date: 2025-11-20 00:47:24.733651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d3035a0b16'
down_revision: Union[str, Sequence[str], None] = '1b4e1dd2e163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('disciplina', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'disciplina')
    # ### end Alembic commands ###
