"""update_tipo_data_constraints_and_size

Revision ID: 5d2c25fa1361
Revises: 960eeeb4ebec
Create Date: 2025-11-20 01:33:14.680080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2c25fa1361'
down_revision: Union[str, Sequence[str], None] = '960eeeb4ebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipo_data', 'nome',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_unique_constraint('uq_tipo_data_nome', 'tipo_data', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tipo_data_nome', 'tipo_data', type_='unique')
    op.alter_column('tipo_data', 'nome',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
