"""Add numero_aula field to horario table

Revision ID: 960eeeb4ebec
Revises: 35d3035a0b16
Create Date: 2025-11-20 01:03:29.750121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960eeeb4ebec'
down_revision: Union[str, Sequence[str], None] = '35d3035a0b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('numero_aula', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'numero_aula')
    # ### end Alembic commands ###
