"""Remove UNIQUE constraint from docente.email

Revision ID: c18dff1fdb7d
Revises: d557c338c7f6
Create Date: 2025-11-19 23:14:39.077373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18dff1fdb7d'
down_revision: Union[str, Sequence[str], None] = 'd557c338c7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_docente_email'), 'docente', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_docente_email'), 'docente', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
