"""Add disciplina field to nota table

Revision ID: c575db45f179
Revises: c18dff1fdb7d
Create Date: 2025-11-20 00:06:14.076377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c575db45f179'
down_revision: Union[str, Sequence[str], None] = 'c18dff1fdb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nota', sa.Column('disciplina', sa.String(length=100), nullable=True))
    op.alter_column('nota', 'nota',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nota', 'nota',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_column('nota', 'disciplina')
    # ### end Alembic commands ###
