"""Remove disciplina, curso_disciplina, and disciplina_docente tables

Revision ID: d557c338c7f6
Revises: 0a8e78f2fbe3
Create Date: 2025-11-19 23:10:13.036907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd557c338c7f6'
down_revision: Union[str, Sequence[str], None] = '0a8e78f2fbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, remove foreign key constraints from dependent tables
    op.drop_constraint(op.f('horario_id_disciplina_4_fkey'), 'horario', type_='foreignkey')
    op.drop_constraint(op.f('horario_id_disciplina_3_fkey'), 'horario', type_='foreignkey')
    op.drop_constraint(op.f('horario_id_disciplina_1_fkey'), 'horario', type_='foreignkey')
    op.drop_constraint(op.f('horario_id_disciplina_2_fkey'), 'horario', type_='foreignkey')
    op.drop_constraint(op.f('nota_id_disciplina_fkey'), 'nota', type_='foreignkey')
    
    # Then, remove the columns from dependent tables
    op.drop_column('horario', 'id_disciplina_2')
    op.drop_column('horario', 'id_disciplina_4')
    op.drop_column('horario', 'id_disciplina_1')
    op.drop_column('horario', 'id_disciplina_3')
    op.drop_column('nota', 'id_disciplina')
    
    # Then, remove the associative tables
    op.drop_table('disciplina_docente')
    op.drop_table('curso_disciplina')
    
    # Finally, remove the main table with its indexes
    op.drop_index(op.f('ix_disciplina_id_disciplina'), table_name='disciplina')
    op.drop_index(op.f('ix_disciplina_user_ra'), table_name='disciplina')
    op.drop_table('disciplina')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nota', sa.Column('id_disciplina', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('nota_id_disciplina_fkey'), 'nota', 'disciplina', ['id_disciplina'], ['id_disciplina'])
    op.add_column('horario', sa.Column('id_disciplina_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('horario', sa.Column('id_disciplina_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('horario', sa.Column('id_disciplina_4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('horario', sa.Column('id_disciplina_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('horario_id_disciplina_2_fkey'), 'horario', 'disciplina', ['id_disciplina_2'], ['id_disciplina'])
    op.create_foreign_key(op.f('horario_id_disciplina_1_fkey'), 'horario', 'disciplina', ['id_disciplina_1'], ['id_disciplina'])
    op.create_foreign_key(op.f('horario_id_disciplina_3_fkey'), 'horario', 'disciplina', ['id_disciplina_3'], ['id_disciplina'])
    op.create_foreign_key(op.f('horario_id_disciplina_4_fkey'), 'horario', 'disciplina', ['id_disciplina_4'], ['id_disciplina'])
    op.create_table('disciplina',
    sa.Column('id_disciplina', sa.INTEGER(), server_default=sa.text("nextval('disciplina_id_disciplina_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_ra', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_ra'], ['usuario.ra'], name='disciplina_user_ra_fkey'),
    sa.PrimaryKeyConstraint('id_disciplina', name='disciplina_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_disciplina_user_ra'), 'disciplina', ['user_ra'], unique=False)
    op.create_index(op.f('ix_disciplina_id_disciplina'), 'disciplina', ['id_disciplina'], unique=False)
    op.create_table('curso_disciplina',
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_disciplina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], name=op.f('curso_disciplina_id_curso_fkey')),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplina.id_disciplina'], name=op.f('curso_disciplina_id_disciplina_fkey')),
    sa.PrimaryKeyConstraint('id_curso', 'id_disciplina', name=op.f('curso_disciplina_pkey'))
    )
    op.create_table('disciplina_docente',
    sa.Column('id_disciplina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_docente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplina.id_disciplina'], name=op.f('disciplina_docente_id_disciplina_fkey')),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], name=op.f('disciplina_docente_id_docente_fkey')),
    sa.PrimaryKeyConstraint('id_disciplina', 'id_docente', name=op.f('disciplina_docente_pkey'))
    )
    # ### end Alembic commands ###
