"""Add ra field to discente table

Revision ID: e18949de1aa9
Revises: 9e3652848aea
Create Date: 2025-11-18 23:59:38.745950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18949de1aa9'
down_revision: Union[str, Sequence[str], None] = '9e3652848aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discente', sa.Column('ra', sa.String(length=13), nullable=False))
    op.create_index(op.f('ix_discente_ra'), 'discente', ['ra'], unique=False)
    op.create_foreign_key(None, 'discente', 'usuario', ['ra'], ['ra'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discente', type_='foreignkey')
    op.drop_index(op.f('ix_discente_ra'), table_name='discente')
    op.drop_column('discente', 'ra')
    # ### end Alembic commands ###
