"""Add ra field to docente table

Revision ID: ed6a7532c77c
Revises: 
Create Date: 2025-11-18 00:21:38.244579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6a7532c77c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docente', sa.Column('ra', sa.String(length=13), nullable=True))
    op.drop_index(op.f('ix_docente_id_usuario'), table_name='docente')
    op.create_index(op.f('ix_docente_ra'), 'docente', ['ra'], unique=False)
    op.drop_constraint(op.f('docente_id_usuario_fkey'), 'docente', type_='foreignkey')
    op.create_foreign_key(None, 'docente', 'usuario', ['ra'], ['ra'])
    op.drop_column('docente', 'id_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docente', sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'docente', type_='foreignkey')
    op.create_foreign_key(op.f('docente_id_usuario_fkey'), 'docente', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_index(op.f('ix_docente_ra'), table_name='docente')
    op.create_index(op.f('ix_docente_id_usuario'), 'docente', ['id_usuario'], unique=False)
    op.drop_column('docente', 'ra')
    # ### end Alembic commands ###
